-   id: graphql-codegen-hook
    name: graphql codegenerator
    description: Runs graphql-codegen generating graphql types.
    entry: graphql-codegen-hook
    language: node
    types: [file, javascript]
    files: \.(tsx|jsx|js|tsx)$
    minimum_pre_commit_version: 0.5.0
